version: '3.8'
services:
  database:
    container_name: postgres_timemachine
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      PGDATA: ${PGDATA}
    image: postgres:13-alpine
    restart: always
    networks:
      - timemachine-backend
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data/pgdata"
  backend:
    build: backend/
    container_name: backend_timemachine
    image: gcr.io/timemanager-330510/timemanager_backend:1.0.0
    environment:
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
    depends_on:
      - database
    ports:
      - "4000:4000"
    networks:
      - timemachine-backend
      - timemachine-frontend
    restart: on-failure
  frontend:
    build: frontend/
    container_name: frontend_timemachine
    image: gcr.io/timemanager-330510/timemanager_backend:1.0.0
    environment:
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - timemachine-frontend
    restart: on-failure

volumes:
  dbdata:

networks: 
  timemachine-frontend: 
  timemachine-backend: