version: '3.8'
services:
  database:
    container_name: postgres_timemachine
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD?err}
      POSTGRES_USER: ${PGUSER?err}
      PGDATA: ${PGDATA?err}
    image: "postgres:${TAG}"
    restart: always
    networks:
      - timemachine-backend
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:${PGDATA}"
  backend:
    build: backend/
    container_name: backend_timemachine
    image: backend_timemachine_image
    environment:
      PGUSER: ${PGUSER?err}
      PGHOST: ${PGHOST?err}
      PGDATABASE: ${PGDATABASE?err}
      PGPASSWORD: ${PGPASSWORD?err}
      PGPORT: ${PGPORT?err}
    depends_on:
      - database
    ports:
      - "${BACKEND_PORT}:4000"
    networks:
      - timemachine-backend
      - timemachine-frontend
    restart: on-failure
  frontend:
    build: frontend/
    container_name: frontend_timemachine
    image: frontend_timemachine_image
    environment:
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:8080"
    networks:
      - timemachine-frontend
    restart: on-failure

volumes:
  dbdata:

networks: 
  timemachine-frontend: 
  timemachine-backend: