apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: backend-deployment-prod
  namespace: timemanager-25-prod
  labels:
    app: backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-prod
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      restartPolicy: Always
      containers:
      - name: backend-prod
        image: gcr.io/timemanager-330510/timemanager_backend:1.0.0
        env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: pg_user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: pg_password
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: pg_database
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: pg_port
                  
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: pg_host
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: backend-service-prod
  namespace: timemanager-25-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 34.76.156.238
  selector:
    app: backend-prod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000