apiVersion: apps/v1 # Deployment
kind: Deployment
metadata:
  name: database-deployment-prod
  namespace: timemanager-25-prod
  labels:
    app: database-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-prod
  template:
    metadata:
      labels:
        app: database-prod
    spec:
      restartPolicy: Always
      containers:
      - name: database-prod
        image: postgres:13-alpine
        env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: pg_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: pg_password
        ports:
        - containerPort: 5432
        imagePullPolicy: IfNotPresent
---
apiVersion: v1 # Service
kind: Service
metadata:
  name: database-service-prod
  namespace: timemanager-25-prod
spec:
  type: ClusterIP
  selector:
    app: database-prod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432